### PR TITLE
Add PS2 Platform

### PR DESCRIPTION
**Pull request by fjtrujy**
## Description

This PR is for adding PS2 platform. How PS2 doesn't natively support RGB565 I have needed to do small changes to support ABGR1555.

Additionally, I have added the CI/CD in the project to keep PS2 version compiling.
You can see the results under the `Actions` tab in the project.

https://github.com/fjtrujy/theodore/actions

Thanks

### CODE REVIEW

**Comment by twinaphex** [comment]
Hi there @Zlika , would be great if you could merge this. This way this core will work on RetroArch PS2.

**Comment by Zlika** [comment]
Thanks for the PR. I'll merge it when I come back to home.
However, I have some small questions:
* How can it work with ABGR1555 without changing the "environ_cb(RETRO_ENVIRONMENT_SET_PIXEL_FORMAT..." line in libretro.c file?
* I recently added a graphical virtual keyboard (you can show it using the select button) but it is configured for RGB565. How you checked that this feature was working on PS2?

**Comment by fjtrujy** [comment]
> Thanks for the PR. I'll merge it when I come back to home.
> However, I have some small questions:
> 
> * How can it work with ABGR1555 without changing the "environ_cb(RETRO_ENVIRONMENT_SET_PIXEL_FORMAT..." line in libretro.c file?
> * I recently added a graphical virtual keyboard (you can show it using the select button) but it is configured for RGB565. How you checked that this feature was working on PS2?

Good questions.
RetroArch doesn't officially support AGBR1555, the solution that I did, was to let RetroArch think that he is using `RGB565`, however, the `RetroArch GFX PS2 Driver` is expecting to receive `AGBR1555`.
 Then, the only thing that I need to do, is a change in the core, to support the proper color correction just for the `PS2` platform, in this case ABGR1555, even still being sent in the `RETRO_ENVIRONMENT_SET_PIXEL_FORMAT` `RGB565`, because as I said, `RetroArch` it-self doesn't support (for now) `AGBR1555`.

I'm going to check the virtual keyboard as well

**Comment by fjtrujy** [comment]
Not sure if this is the proper behavior.
If not, where can I change the color correction of the virtual keyboard?

Thanks

Screenshot 2020-05-22 at 10 16 47

**Comment by Zlika** [comment]
It's not the good colors. The Enter key must be yellow, not blue. I guess you have to make some #ifdef changes in src/vkeyb/ui.c to convert on the fly the RGB565 data to ABGR1555.

**Comment by fjtrujy** [comment]
No, I think that the issue is in the img2c.py, script.
Overthere you should create 2 `const uint16_t KEYB_***_IMG_DATA[]`, per file with a `#ifdef` precompiled constraints.

Then in compilation time that processor will take one binary (png) or the other.

```
def rgba888ToRgb565(rgba):
    return ((rgba[0] >> 3) << 11) | ((rgba[1] >> 2) << 5) | (rgba[2] >> 3)

....................

print("const uint16_t " + c_var_base_name + "_IMG_DATA[] =")
print("{")
for y in range(0, img.height):
    print("  ", end='')
    for x in range(0, img.width):
        print('0x{0:0{1}X}'.format(rgba888ToRgb565(pixels[x, y]), 4), end='')
        if ((y != img.height - 1) or (x != img.width - 1)):
           print(",", end='')
    print("")
print("};")
```

**Comment by fjtrujy** [comment]
I have fixed the VKeyboard color correction as well

Screenshot 2020-05-22 at 11 54 21

Thanks

**Comment by Zlika** [comment]
I think there is still a last problem to fix: it is possible to set the keyboard transparency using a core's option. This transparency is managed in the "blend" function in file src/vkeyb/ui.c. This function splits the foreground/background colors into rgb components to apply the transparency. This function must be changed to be compatible with ABGR1555. You can check by yourself: if you change the "keyboard transparency" option of the core to add a little transparency than the colors should be wrong with your current code.

**Comment by fjtrujy** [comment]
Hello @Zlika ,
Thanks!
Step by step I will change your whole core 😎 

Screenshot 2020-05-22 at 13 42 42

Thanks!

**Comment by Zlika** [comment]
Muchas gracias amigo ! :-)

**Pull request merged**
