### PR TITLE
Remove security flags

### PR DESCRIPTION
**Pull request by cucholix**
Remove security flags

### CODE REVIEW

**Comment by Zlika** [comment]
Hi!
Thanks for this PR. However I cannot merge it because it removes the compiler's security flags for all platforms, instead of removing it only for the WiiU platform. Can you rework this PR to only remove these flags for the WiiU platform? Thanks

**Comment by cucholix** [comment]
But this is not the main branch

**Comment by Zlika** [comment]
Yes, but I plan to merge this branch into master when everything will be fixed. Moreover this seems to be a real problem because I just saw that the retroarch build bot does not build the core for WiiU since I introduced this security flag, so this is definitively something that must be fixed.

**Comment by cucholix** [comment]
Ok, I'm working on my fork, will report later =)

**Pull request closed without merging**
