### PR TITLE
Instruction to add the core into the Steam version of RetroArch

### PR DESCRIPTION
**Pull request by sporniket**

### CODE REVIEW

**Comment by sporniket** [comment]
This is what you can get with the info file :

User friendly name
image

Detailed info
Capture d’écran du 2022-09-02 21-58-40

**Comment by Zlika** [comment]
Thanks for your PR. There is already a theodore_libretro.info file available in https://github.com/libretro/libretro-super/blob/master/dist/info/ so I don't know if it is interesting to duplicate it here. I would also need to update it in libretro-super because cheats are supported now.

**Comment by sporniket** [comment]
Ok, that is where this info file was... I updated the proposed README and removed the info file.

**Comment by Zlika** [comment]
Thanks!

**Pull request merged**
